# -*- coding: utf-8 -*-
""""ЛP_12_Чисельне інтегрування.ipynb" Ісаєв К.М 2-9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiHeBoDid6X36ASHBbNjhzblVuN35gIh

Завдання 3. Визначити інтеграм методом трапецій
"""

#Обчислення інтегралу методом трапецій

from scipy import integrate
import numpy as np

# Функція підінтегрального виразу
def f(x):
    return 1 / (x**2 - 1)

# Межі інтегрування та кількість розбиттів
a, b, n = 2.0, 3.6, 20

# Обчислення інтегралу методом трапецій
def trapezoidal_rule(f, a, b, n):
    h = (b - a) / n
    s = 0.5 * (f(a) + f(b))
    x = a
    for i in range(1, n):
        x += h
        s += f(x)
    integral = h * s
    return integral

# Результат методу трапецій
integral = trapezoidal_rule(f, a, b, n)
print("Trapezia method result:", round(integral, 5))

# Перевірка за допомогою вбудованої функції SciPy
v, err = integrate.quad(f, a, b)
print("Check with SciPy quad method:", round(v, 5))

"""Завдання 1. Метод прямокутників (правих, лівих і середніх)"""

#Обчислення інтеграла методом прямокутників
from scipy import integrate
import numpy as np

a, b, n = 0.4, 1.2, 10
h = (b - a) / n  # крок

# Підінтегральна функція
def f1(x):
    return 1 / (x + 0.5)

# Метод лівих прямокутників
def left_rectangle(f1, a, b):
    s = 0
    for i in range(0, n):
        s += f1(a + i * h)
    return s * h

# Метод правих прямокутників
def right_rectangle(f1, a, b):
    s = 0
    for i in range(1, n + 1):
        s += f1(a + i * h)
    return s * h

# Метод середніх прямокутників
def middle_rectangle(f1, a, b):
    s = 0
    for i in range(0, n):
        s += f1(a + (i + 0.5) * h)
    return s * h


print("Left rectangle:", round(left_rectangle(f1, a, b), 5))
print("Right rectangle:", round(right_rectangle(f1, a, b), 5))
print("Middle rectangle:", round(middle_rectangle(f1, a, b), 5))

# Перевірка за допомогою scipy
v, err = integrate.quad(f1, a, b)
print("Check with SciPy quad method:", round(v, 5))

"""Завдання 2. Метод Симпсона"""

#Обчислення інтеграла методом Симпсона
from scipy import integrate
import numpy as np

# Функція підінтегрального виразу
def f(x):
    return np.cos(x) / (2 + x)

# Межі інтегрування та n
a, b, n = 0.4, 1.2, 8
h = (b - a) / n

# Реалізація методу Сімпсона
def simpson_rule(f, a, b, n):
    s = f(a) + f(b)

    for i in range(1, n):
        x = a + i * h
        if i % 2 == 0:
            s += 2 * f(x)
        else:
            s += 4 * f(x)

    return s * h / 3

# Результат методу Сімпсона
result = simpson_rule(f, a, b, n)
print("Simpson method:", round(result, 6))

# Перевірка через SciPy
v, err = integrate.quad(f, a, b)
print("Check with SciPy quad method:", round(v, 6))