# -*- coding: utf-8 -*-
""""ЛР11. Метод найменших квадратів.ipynb" Ісаєв К.М. 2-9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hnSrZ6yChnTFPXsOZ3FSh7SV4_jUTix7

Метод найменших квадратів (МНК)

1.Наближення прямою.
Реалізація метода вручну
"""

import numpy as np
import matplotlib.pyplot as plt

# Функція
def func(x):
    return x**2 * np.sin(x)

# Вхідні дані
x = np.array([i * 0.1 for i in range(1, 11)])   # 0.1, 0.2, ..., 1.0
y = np.array([func(xi) for xi in x])

print('x =', x)
print('y =', y)

# Обчислення коефіцієнтів a та b для лінії y = a*x + b
n = len(x)
x_mean = np.mean(x)
y_mean = np.mean(y)

a = (n * np.sum(x * y) - np.sum(x) * np.sum(y)) / (n * np.sum(x**2) - np.sum(x)**2)
b = y_mean - a * x_mean

print(f"Рівняння лінії: y = {a:.4f}x + {b:.4f}")

# Графік
plt.scatter(x, y, label='Точки даних')
plt.plot(x, a * x + b, label='Лінія найкращої підгонки')

plt.xlabel('x')
plt.ylabel('y')
plt.title('МНК. Наближення прямою')
plt.legend()
plt.grid(True)
plt.show()

""" Реалізація МНК наближення прямою за допомогою polyfit()"""

import numpy as np
import matplotlib.pyplot as plt

# Функція
def func(x):
    return x**2 * np.sin(x)

# Вхідні дані
x = np.array([i * 0.1 for i in range(1, 11)])
y = np.array([func(xi) for xi in x])

print('x =', x)
print('y =', y)

# polyfit для лінії (ступінь 1)
coefficients = np.polyfit(x, y, 1)
a, b = coefficients

print(f"Рівняння лінії: y = {a:.4f}x + {b:.4f}")

polynomial = np.poly1d(coefficients)

# Графік
plt.scatter(x, y, label='Точки даних')
x_line = np.linspace(min(x), max(x), 200)
plt.plot(x_line, polynomial(x_line), label='Лінія найкращої підгонки (polyfit)')

plt.title('МНК за допомогою polyfit() — пряма')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.grid(True)
plt.show()

""" 3  Реалізація МНК наближення параболою за допомогою polyfit()"""

# ЧАСТИНА 3 — Наближення параболою

import numpy as np
import matplotlib.pyplot as plt

# Функція
def func(x):
    return x**2 * np.sin(x)

# Вхідні дані
x = np.array([i * 0.1 for i in range(1, 11)])
y = np.array([func(xi) for xi in x])

print('x =', x)
print('y =', y)

# polyfit для полінома другого порядку
coefficients = np.polyfit(x, y, 2)
a, b, c = coefficients

print(f"Рівняння параболи: y = {a:.4f}x^2 + {b:.4f}x + {c:.4f}")

polynomial = np.poly1d(coefficients)

# Графік
plt.scatter(x, y, label='Точки даних')
x_line = np.linspace(min(x), max(x), 200)
plt.plot(x_line, polynomial(x_line), label='Апроксимація поліномом 2-го порядку')

plt.title('МНК. Поліном другого порядку')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.grid(True)
plt.show()

"""
 Наближення параболою за допомогою least_squares ()"""

# ЧАСТИНА 4 — Наближення параболою через least_squares

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import least_squares

# Функція
def func(x):
    return x**2 * np.sin(x)

# Вхідні дані
x = np.array([i * 0.1 for i in range(1, 11)])
y = np.array([func(xi) for xi in x])

print('x =', x)
print('y =', y)

# Функція похибок для полінома a0 + a1*x + a2*x^2
def fun(a, x, y):
    return a[0] + a[1] * x + a[2] * x**2 - y

# Початкове наближення
a0 = np.array([1.0, 1.0, 1.0])

# МНК через least_squares
res_lsq = least_squares(fun, x0=a0, args=(x, y))
a0_opt, a1_opt, a2_opt = res_lsq.x

print("a0 = %.4f, a1 = %.4f, a2 = %.4f" % (a0_opt, a1_opt, a2_opt))

# Апроксимаційна функція
def approx(x):
    return a0_opt + a1_opt * x + a2_opt * x**2

# Графік
x_p = np.linspace(min(x), max(x), 200)
y_p = approx(x_p)

plt.plot(x, y, 'o', label='Дані f(x) = x^2 sin(x)')
plt.plot(x_p, y_p, label='МНК апроксимація параболою (least_squares)')
plt.title("МНК наближення параболою")
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.grid(True)
plt.show()