# -*- coding: utf-8 -*-
"""Лаб 9 Ісаєв. К.М

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hl7KLwXq4eAtIGzoPUiDE1wvLu00urmf
"""

#Лабораторна робота 10. Наближення функцій багаточленом Тейлора.
import sympy as sp
import numpy as np
import matplotlib.pyplot as plt

# Символьна змінна і функція для 8 варіанта
x = sp.symbols('x')
f = x * sp.sin(x)

# Перші три похідні
f1 = sp.diff(f, x)
f2 = sp.diff(f1, x)
f3 = sp.diff(f2, x)

# Виводимо похідні
print("f'(x) =", f1)
print("f''(x) =", f2)
print("f'''(x) =", f3)

# Точка розкладу a = 0
x0 = 0
f_x0 = f.subs(x, x0).evalf()
f1_x0 = f1.subs(x, x0).evalf()
f2_x0 = f2.subs(x, x0).evalf()
f3_x0 = f3.subs(x, x0).evalf()

# Поліном Тейлора 3-го порядку
T = f_x0 + f1_x0*(x - x0) + (f2_x0/2)*(x - x0)**2 + (f3_x0/6)*(x - x0)**3

print("\nf(0) =", f_x0.round(3))
print("T(x) =", T.evalf())

# Побудова графіка
x_vals = np.linspace(-2, 2, 1000)
f_vals = np.array([f.subs(x, xi).evalf() for xi in x_vals])
T_vals = np.array([T.subs(x, xi).evalf() for xi in x_vals])

plt.figure(figsize=(10, 6))
plt.plot(x_vals, f_vals, label='f(x) = x*sin(x)', color='blue')
plt.plot(x_vals, T_vals, label='Поліном Тейлора (3-го порядку)', color='red', linestyle='--')
plt.legend()
plt.xlabel('x')
plt.ylabel('y')
plt.title('Графік функції та наближення багаточленом Тейлора')
plt.grid(True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import approximate_taylor_polynomial

# Функція для 8 варіанта
def f(x):
    return x * np.sin(x)

x = np.linspace(-2.0, 2.0, num=400)

plt.figure(figsize=(10, 6))
plt.plot(x, f(x), label="f(x) = x*sin(x)", color='blue')

degree = 3  # ступінь полінома
taylor = approximate_taylor_polynomial(f, 0, degree, 1)
print("taylor =", taylor)

plt.plot(x, taylor(x), label=f"Поліном Тейлора (degree={degree})", color='red', linestyle='--')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0.0, shadow=True)
plt.xlabel("x")
plt.ylabel("y")
plt.title("Графік функції та наближення багаточленом Тейлора")
plt.tight_layout()
plt.grid()
plt.show()

# Побудова полінома Тейлора за допомогою approximate_taylor_polynomial (10-го порядку)

import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import approximate_taylor_polynomial

# Задана функція для 8 варіанта
def f(x):
    return x * np.sin(x)

x = np.linspace(-2.0, 2.0, num=400)

plt.figure(figsize=(10, 6))
plt.plot(x, f(x), label="f(x) = x*sin(x)", color='blue')

degree = 10  # ступінь полінома Тейлора
taylor = approximate_taylor_polynomial(f, 0, degree, 1)

print("Поліном Тейлора 10-го порядку:")
print(taylor)

# Побудова графіка
plt.plot(x, taylor(x), label=f"Поліном Тейлора (degree={degree})", color='red', linestyle='--')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0.0, shadow=True)
plt.xlabel("x")
plt.ylabel("y")
plt.title("Графік функції та її наближення поліномом Тейлора (10-го порядку)")
plt.tight_layout()
plt.grid()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import approximate_taylor_polynomial
x = np.linspace(-10.0, 10.0, num=100)
plt.plot(x, np.sin(x), label="sin curve")
for degree in np.arange(1, 15, step=2):
    sin_taylor = approximate_taylor_polynomial(np.sin, 0, degree, 1,
                                               order=degree + 2)
    plt.plot(x, sin_taylor(x), label=f"degree={degree}")
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left',
           borderaxespad=0.0, shadow=True)
plt.tight_layout()
plt.axis([-10, 10, -10, 10])
plt.show()